# Generated by Django 5.2.9 on 2025-12-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_category_auction_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='condition',
            field=models.CharField(choices=[('NEW', '새 상품'), ('USED_S', 'S급 (미사용)'), ('USED_A', 'A급 (사용감 적음)'), ('USED_B', 'B급 (보통)'), ('USED_C', 'C급 (하자 있음)')], default='USED_A', max_length=10),
        ),
        migrations.AddField(
            model_name='auction',
            name='shipping_payer',
            field=models.CharField(choices=[('SELLER', '판매자 부담 (무료배송)'), ('BUYER', '구매자 부담 (착불)')], default='BUYER', max_length=10),
        ),
    ]
